### ISSUE TITLE
개발환경 재정리

### ISSUE THREAD

**Issue by kyungilpark** [naver/smarteditor2#119]
### TODO
- [x] webpack 세팅
  - [x] webpack-dev-server 세팅
  - [x] 빌드 환경 세팅
- [x] gitbook 세팅
  - [x] 사용자 가이드 전환 작업
- [x] eslint 세팅
  - 디테일한 룰은 추후 결정
  - [x] fix lint error (#120)
- [x] jest 세팅
  - 테스트코드는 별도 작성
  - [x] 빌드 환경 세팅 후 샘플 TC 작성
- [x] travis-ci 세팅
